#!/usr/bin/expect 
set timeout 20 
 
if { [llength $argv] < 5} { 
    puts "Usage:" 
    #puts "$argv0 local_fddile remote_path" 
    puts "$argv0 host username password local_file remote_file" 
    exit 1 
} 
 
set host [lindex $argv 0]
set username [lindex $argv 1]
set password [lindex $argv 2]
set local_file [lindex $argv 3]
set remote_file [lindex $argv 4]
spawn scp  $local_file $username@$host:$remote_file
 
set passwderror 0 
 
#spawn scp $local_file $remote_path 
 
expect { 
    "*assword:*" { 
        if { $passwderror == 1 } { 
        puts "passwd is error" 
        exit 2 
        } 
        set timeout 1000 
        set passwderror 1 
        send "$password\r" 
        exp_continue 
    } 
    "*es/no)?*" { 
        send "yes\r" 
        exp_continue 
    } 
    timeout { 
        puts "connect is timeout" 
        exit 3 
    } 
}  
